# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Mux < Formula
  desc "tmux session manager with interactive TUI"
  homepage "https://github.com/JeongJaeSoon/mux"
  version "0.1.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/JeongJaeSoon/mux/releases/download/v0.1.0/mux_darwin_amd64.tar.gz"
      sha256 "c9b5febe29c293e5ccff9016ce43f7f9d648156b95f892ba91a7658708bf621f"

      define_method(:install) do
        bin.install "mux"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/JeongJaeSoon/mux/releases/download/v0.1.0/mux_darwin_arm64.tar.gz"
      sha256 "76813c55e1c248eaa9993aa107c81a4e022ce72531dafc2d699f0354e15afb46"

      define_method(:install) do
        bin.install "mux"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/JeongJaeSoon/mux/releases/download/v0.1.0/mux_linux_amd64.tar.gz"
      sha256 "c5dde2b16f354d13968d4360de4dc7991e9245b1e8405fa79f1412524529a43b"
      define_method(:install) do
        bin.install "mux"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/JeongJaeSoon/mux/releases/download/v0.1.0/mux_linux_arm64.tar.gz"
      sha256 "50c6955b42d116faf5577cbed9edfe956849de8ef5f6d962b8ab95b91f16f084"
      define_method(:install) do
        bin.install "mux"
      end
    end
  end
end
